### ISSUE TITLE
Changing word embedding size from 200 to 300 causes NoneType is not Iterable 

### ISSUE THREAD

**Issue by saurabhvyas** [pandeykartikey/Hierarchical-Attention-Network#1]
So I am running the jupyter notebook, with pretrained embedding of 300 size, I changed embedsize to 300, but I am getting NoneType is iterable error, but it goes away if load pretrained word2vec of size 200, everything else is the same, is the size hardcoded in the model ?

Also changing batch size from 64 to 80 caused the same error

**Comment by pandeykartikey** [comment]
For embedding size, that problem occurs because I have to load the embedding layer from the word2vec model and I did not use the variable embed size there. But for batch_size it should not have caused a problem as it is defined at only one place. 
Could you look into it again?

**Comment by saurabhvyas** [comment]
I did look at it, couldn't identify the cause, but I am going to close it for now, I am using some other keras implementation, but I really appreciate your work.
